---
- #hosts: localhost
  hosts: dev
  #become: True
  vars:
    ansible_python_interpreter: /bin/python3
  tasks:
    - name: Start the container
      docker_container:
        name: dockeransible
        image: "ahmedabdelgawad23/dockeransible:{{DOCKER_TAG}}"
        state: started
        published_ports:
         - 0.0.0.0:8081:8080